#!/bin/sh
#
# Installation script for Rasbian Wheezy. The installation script can be
# run after compiling the binaries.
#
# Installation:
#
# a) make
# 
# b) cd doc/man/; ./mkmag3110d
# 
# c) sudo ./install (this script)
#
# d) sudo raspi-config (to enable I2C) 
#
# e) sudo service mag3110d start
# 
# f) tail -f /var/log/mag3110d.log
#
# g) sudo update-rc.d mag3110d defaults (optional)
# 
#
# The directories used and files created by this script:
#
# /etc/init.d/mag3110d                - init script
# /etc/logrotate.d/mag3110d           - log rotation file
# /etc/mag3110d_config                - configuration file
# /usr/share/man/man1/mag3110d.1      - manual page
# /usr/sbin/mag3110d                  - field reading daemon
# /var/lib/mag3110d/                  - live field data
#
# Sat Nov  8 17:29:20 CET 2014
# Edit: Thu Feb 12 22:11:38 CET 2015
# 
# Jaakko Koivuniemi
#


# source directory for 'Mag3110d'
SOURCEDIR=${PWD}
SOURCEBIN=${SOURCEDIR}/
SOURCEMAN=${SOURCEDIR}/doc

# binary executables 
BINDIR=/usr/sbin

# manual pages
MANDIR=/usr/share/man/man1

# mag3110d.log log rotation  
LOGROTADIR=/etc/logrotate.d

# init script
INITDIR=/etc/init.d

# for pipicpowerd_conf configuration file
CONFDIR=/etc

# live data 
VARLIBDIR=/var/lib

# binary executables
BINS='mag3110d'

if [ -d $SOURCEBIN ]; then
  echo "Copy binary executables to ${BINDIR}"
  for item in $BINS;
  do
    if [ -r ${SOURCEBIN}/${item} ]; then
       echo "... ${item}"
       /usr/bin/install -C -m 755 ${SOURCEBIN}/${item} ${BINDIR}
    fi 
  done
else
  echo "Source directory ${SOURCEBIN} does not exist"
fi

if [ -d $SOURCEMAN ]; then
  echo "Copy manual pages to ${MANDIR}"
  for item in $BINS;
  do
    if [ -r ${SOURCEMAN}/$item.1 ]; then
       echo "... ${item}.1"
       /usr/bin/install -C -m 664 ${SOURCEMAN}/${item}.1 ${MANDIR}
    fi 
  done
else
  echo "Source directory ${SOURCEMAN} does not exist"
fi

if [ ! -r ${LOGROTADIR}/mag3110d ]; then
  echo "Write log rotation file ${LOGROTADIR}/mag3110d"
  /usr/bin/install -C -m 644 ${SOURCEDIR}/mag3110d.lrota ${LOGROTADIR}
  /bin/mv ${LOGROTADIR}/mag3110d.lrota ${LOGROTADIR}/mag3110d
else
  echo "Log rotation file ${LOGROTADIR}/mag3110d already exists"
fi

if [ ! -x ${INITDIR}/mag3110d ]; then
  echo "Write init script ${INITDIR}/mag3110d"
  /usr/bin/install -C -m 755 ${SOURCEDIR}/mag3110d.sh ${INITDIR} 
  /bin/mv ${INITDIR}/mag3110d.sh ${INITDIR}/mag3110d
else
  echo "Init script ${INITDIR}/mag3110d already exists"
fi

if [ ! -r ${CONFDIR}/mag3110d_config ]; then
  echo "Write default configuration file ${CONFDIR}/mag3110d_config"
  /usr/bin/install -C -m 664 ${SOURCEDIR}/mag3110d_config ${CONFDIR} 
else
  echo "Configuration file ${CONFDIR}/mag3110d_config already exists" 
fi

if [ -d /var/lib/mag3110d ]; then
  echo "Directory /var/lib/mag3110d already exists"
else
  echo "Create directory /var/lib/mag3110d"
  /bin/mkdir -m 775 /var/lib/mag3110d
fi

echo "Run 'update-rc.d mag3110d defaults' to automatically start at boot time"
